<a href="https://colab.research.google.com/github/Harshita1204/python/blob/main/Data_preprocessing.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
# data preprocessing
import numpy as np
import pandas as pd
from google.colab import files
uploaded = files.upload()


Saving child_labour.xlsx to child_labour.xlsx


In [ ]:
# in dictionary, concept of keys values:Key: A unique identifier for a value. Keys must be immutable (e.g., strings, numbers, tuples).
# Value: The data associated with a key. Values can be of any data type and can be duplicated.
for key, value in uploaded.items():
   print('user uploaded files "{name}" with length {length} bytes'.format(name=key, length=len(value)))

user uploaded files "child_labour.xlsx" with length 8292 bytes


In [ ]:
import io
data = pd.read_excel(io.BytesIO(uploaded['child_labour.xlsx']))
data.head()

state  age  salary married
0   haryana    4     NaN     yes
1   haryana    5   687.0     yes
2  himachal    5   500.0      no
3     assam    5   400.0     no 
4       NaN    6   876.0      no

In [18]:
x = data.iloc[:, :-1].values
xx = data.iloc[:, 1:3].values
print(x)
print(xx)

[['haryana' 4 nan]
 ['haryana' 5 687.0]
 ['himachal' 5 500.0]
 ['assam' 5 400.0]
 [nan 6 876.0]
 ['punjab' 9 700.0]]
[[  4.  nan]
 [  5. 687.]
 [  5. 500.]
 [  5. 400.]
 [  6. 876.]
 [  9. 700.]]


In [20]:
import numpy as np
from sklearn.impute import SimpleImputer
imputer= SimpleImputer(missing_values=np.nan,strategy='mean')
imputer= imputer.fit(x[:,1:3])
x[:,1:3]=imputer.transform(x[:,1:3])
print(x)

imputer = SimpleImputer(missing_values=np.nan , strategy = 'median')
imputer = imputer.fit(xx[:,1:3])
xx[:,1:3] = imputer.transform(xx[:,1:3])
print(xx)

[['haryana' 4.0 632.6]
 ['haryana' 5.0 687.0]
 ['himachal' 5.0 500.0]
 ['assam' 5.0 400.0]
 [nan 6.0 876.0]
 ['punjab' 9.0 700.0]]
[[  4. 687.]
 [  5. 687.]
 [  5. 500.]
 [  5. 400.]
 [  6. 876.]
 [  9. 700.]]


In [21]:
from sklearn.preprocessing import LabelEncoder
labelencoder_x=LabelEncoder()
x[:,0]=labelencoder_x.fit_transform(x[:,0])
print(x)

[[1 4.0 632.6]
 [1 5.0 687.0]
 [2 5.0 500.0]
 [0 5.0 400.0]
 [4 6.0 876.0]
 [3 9.0 700.0]]
