<a href="https://colab.research.google.com/github/Harshita1204/python/blob/main/questions.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
# import numpy library
import numpy as np

# Q1: create a 1D numpy array containing first 10 natural numbers
arr1=np.arange(1,11) # numbers from 1 to 10 as last number is not included
print("first 10 natural numbers:",arr1)

first 10 natural numbers: [ 1  2  3  4  5  6  7  8  9 10]


In [ ]:
import numpy as np

# Q2: create a numpy array from 5 to 50 wit"h step of 5
arr2=np.arange(5,51,5) # start = 5, end = 50 as 51 (end) not included , step/ gap=5
print("Array from 5 to 50 with the step of 5",arr2)

Array from 5 to 50 with the step of 5 [ 5 10 15 20 25 30 35 40 45 50]


In [ ]:
import numpy as np

# Q3: convert the python list into a numpy array and display data type

lst= [12,52,38,41,56] # python list
arr3 = np.array(lst) # convert list of numpy array
print("Converting the python list into the numpy array : ",arr3)
print("Datatype: ",arr3.dtype) # display data type


Converting the python list into the numpy array :  [12 52 38 41 56]
Datatype:  int64


In [ ]:
import numpy as np

# Q4: create a numpy array of size 3*3 and reshape it into 1D

arr4 = np.arange(1,10).reshape(3,3) # create 3*3 array
print ("2D array:\n",arr4)

arr4_1D = arr4.reshape(9) # reshape 2D array into 1D array
print("1D array: ",arr4_1D)

2D array:
 [[1 2 3]
 [4 5 6]
 [7 8 9]]
1D array:  [1 2 3 4 5 6 7 8 9]


In [ ]:
import numpy as np

# Q5: create a numpy array of zeroes(4,2) and ones(2,4)
zeros_arr = np.zeros((4,2)) # array of zeroes
ones_arr = np.ones((2,4)) # array of ones

print(" zeros array: ", zeros_arr)
print(" ones array: ",ones_arr)

 zeros array:  [[0. 0.]
 [0. 0.]
 [0. 0.]
 [0. 0.]]
 ones array:  [[1. 1. 1. 1.]
 [1. 1. 1. 1.]]


In [ ]:
import numpy as np
 # random number from normal distribution
a= np.random.normal(0,1,5) # generate 5 values randomly

print ("Data: ",a)
print ("mean: ",np.mean(a))
print ("median: ",np.median(a))
#print("mode:",np.mode(a))

Data:  [0.74835028 0.84583153 0.18656785 0.69221495 0.27908637]
mean:  0.5504101965616541
median:  0.6922149484405826


In [7]:
import numpy as np
arr1 = np.arange(1,10).reshape(3,3)
arr2 = np.arange(11,20).reshape(3,3)
print(arr1*arr2)

[[ 11  24  39]
 [ 56  75  96]
 [119 144 171]]


In [11]:
import numpy as np
# perform element wise addition of two numpy arrays of size 5
arr1=np.arange(1,6)
arr2=np.arange(6,11)
print(arr1+arr2)

[ 7  9 11 13 15]


In [15]:
import numpy as np
# find the square root of each element of a numpy array
arr1=np.arange(1,5)
print(np.sqrt(arr1))

[1.         1.41421356 1.73205081 2.        ]


In [ ]:
import numpy as np

# Example with a simple array
data = np.array([1, 2, 3, 4, 5])
std_dev = np.std(data)
print(f"Data: {data}")
print(f"Standard deviation: {std_dev}")

# Example with a larger, more varied array
data_large = np.array([10, 12, 23, 23, 16, 23, 21, 16])
std_dev_large = np.std(data_large)
print(f"\nData (larger set): {data_large}")
print(f"Standard deviation (larger set): {std_dev_large}")