<a href="https://colab.research.google.com/github/Harshita1204/python/blob/main/questions.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [2]:
# import numpy library
import numpy as np

# Q1: create a 1D numpy array containing first 10 natural numbers
arr1=np.arange(1,11) # numbers from 1 to 10 as last number is not included
print("first 10 natural numbers:",arr1)

first 10 natural numbers: [ 1  2  3  4  5  6  7  8  9 10]


In [3]:
import numpy as np

# Q2: create a numpy array from 5 to 50 wit"h step of 5
arr2=np.arange(5,51,5) # start = 5, end = 50 as 51 (end) not included , step/ gap=5
print("Array from 5 to 50 with the step of 5",arr2)

Array from 5 to 50 with the step of 5 [ 5 10 15 20 25 30 35 40 45 50]


In [5]:
import numpy as np

# Q3: convert the python list into a numpy array and display data type

lst= [12,52,38,41,56] # python list
arr3 = np.array(lst) # convert list of numpy array
print("Converting the python list into the numpy array : ",arr3)
print("Datatype: ",arr3.dtype) # display data type


Converting the python list into the numpy array :  [12 52 38 41 56]
Datatype:  int64


In [8]:
import numpy as np

# Q4: create a numpy array of size 3*3 and reshape it into 1D

arr4 = np.arange(1,10).reshape(3,3) # create 3*3 array
print ("2D array:\n",arr4)

arr4_1D = arr4.reshape(9) # reshape 2D array into 1D array
print("1D array: ",arr4_1D)

2D array:
 [[1 2 3]
 [4 5 6]
 [7 8 9]]
1D array:  [1 2 3 4 5 6 7 8 9]


In [9]:
import numpy as np

# Q5: create a numpy array of zeroes(4,2) and ones(2,4)
zeros_arr = np.zeros((4,2)) # array of zeroes
ones_arr = np.ones((2,4)) # array of ones

print(" zeros array: ", zeros_arr)
print(" ones array: ",ones_arr)

 zeros array:  [[0. 0.]
 [0. 0.]
 [0. 0.]
 [0. 0.]]
 ones array:  [[1. 1. 1. 1.]
 [1. 1. 1. 1.]]
